{ :artist_name=>"", 
  :smart_type=>"tags", 
  :sort=>"hot", 
  :html_name=>"Indie + rock", 
  :description=>"", 
  :relative_name=>"Indie + rock", 
  :relative_short_name=>"Indie + rock", 
  :smart_id=>"tags:rock+indie", 
  :path=>"/mix_sets/tags:rock+indie", 
  :name=>"Indie + rock", 
  :web_path=>"/explore/indie+rock/hot", 

  :mixes=> [ <MixModule::Mix:0x007fc10444fcb0 
  	         @info={:preview=> { :user=> <MixModule::TracksUser:0x007fc10444ec48 @info={:preview=>{:id=>"7280726", 
      																						       :login=>"ZarryUghh", 
      																						       :path=>"/users/7280726", 
      																						       :web_path=>"/zarryughh", 
      																						       :avatar_urls=>"http://8tracks.imgix.net/avatars/007/280/726/61325.original.jpg"}}>, 
      :liked_by_current_user=>"false", 
      :likes_count=>"153", 
      :certification=>"gold", 
      :duration=>"1778", 
      :tracks_count=>"8", 
      :id=>"4558655", 
      :path=>"/mixes/4558655", 
      :web_path=>"/zarryughh/hes-so-fine", 
      :name=>"\"hes so fine\"", 
      :user_id=>"7280726", 
      :published=>"true", 
      :cover_urls=>"http://8tracks.imgix.net/i/002/453/307/BuDqNUnCYAA1UZP-6579.jpg", 
      :description=>"every time i look at harry im like dAYUM", 
      :plays_count=>"1959", 
      :tag_list_cache=>"harry styles, indie, rock, chill, vibes", 
      :first_published_at=>"2014-08-02T21:01:49Z", 
      :first_published_at_timestamp=>"1407013309"}}, 

      :tags_list => ["indie", "rock"], 

  :pagination => { :current_page=>"1", 
     :per_page=>"12", 
     :offset_by=>"0", 
     :next_page=>"2", 
     :previous_page=>"", 
     :total_entries=>"23085", 
     :total_pages=>"1924", 
     :next_page_path=>"/mix_sets/tags:rock+indie?page=2&per_page=12"}}

